### ISSUE TITLE
Pins to GPIOs

### ISSUE THREAD

**Issue by bodnarbalazs** [bubao/Max6675-Raspberry-pi-nodejs#1]
Hi Bubao,
I've just started working with microcontrollers and from the documentation it wasn't clear to which pins should I connect the SCK, CS and SO. GND I assume is to ground and VCC is either 5V or 3.3V since the module can work with both. Thanks for the clarification and the work.
B

**Comment by bubao** [comment]
## DEMO

```js
const CS = 4;
const SCK = 24;
const SO = [25, 12, 16, 20, 21];
const UNIT = 1;
const max6675 = new Max6675();
max6675.setPin(CS, SCK, SO, UNIT);

(async () => {
	while (true) {
		const { temp, unit } = max6675.readTemp();
		if (temp.length)
			console.log(`${new Date()}:${temp.map(item => item + unit)}`);
		await max6675.sleep(2000);
	}
})();
```

![PIN](https://user-images.githubusercontent.com/13029001/107857184-c58d7100-6e67-11eb-93b1-8a4ebc9c9309.png)

The PINs value is BCM GPIOs (green) 

![rpiblusleaf.png](https://raw.githubusercontent.com/splitbrain/rpibplusleaf/master/rpiblusleaf.png)

**Comment by bodnarbalazs** [comment]
Thanks
